name: Publish Markdown and static assets to 'docs' folder

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Display version from package.json
        run: node -p "require('./package.json').version"
      - name: Build
        run: npm run build
      - name: Publish to NPM
        run: npm publish
