name: Publish to NPM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Determine version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Display version
        run: echo ${{ steps.package-version.outputs.current-version}}
      - name: Build
        run: npm run build
      - name: Publish to NPM
        run: npm publish
